import { createRoomStateEnvelope } from './room-state-builders.js'

export function createRoomState() {
  const now = Date.now()
  const updatedAt = new Date(now).toISOString()

  return createRoomStateEnvelope({
    now,
    updatedAt,
    agents: [
      {
        id: 'agent1',
        name: '房间主控',
        role: 'controller',
        emoji: '\u{1F3AE}',
        theme: 'pixel-room-controller',
        status: 'working',
        activityLabel: '正在统筹任务',
        currentTask: '维护 room-dashboard 的开发与生产环境',
        isDefault: true,
        canDispatchTo: ['agent2', 'agent3', 'agent4'],
        lastSeenAt: updatedAt,
        roomZone: 'center-console',
      },
      {
        id: 'agent2',
        name: '执行助手',
        role: 'work',
        emoji: '\u{1F4BC}',
        theme: 'pixel-room-work',
        status: 'idle',
        activityLabel: '等待执行任务',
        currentTask: '待命中',
        isDefault: false,
        canDispatchTo: [],
        lastSeenAt: new Date(now - 2 * 60 * 1000).toISOString(),
        roomZone: 'work-desk',
      },
      {
        id: 'agent3',
        name: '研究助手',
        role: 'study',
        emoji: '\u{1F4DA}',
        theme: 'pixel-room-study',
        status: 'thinking',
        activityLabel: '整理视觉规格',
        currentTask: '研究像素房间状态映射',
        isDefault: false,
        canDispatchTo: [],
        lastSeenAt: new Date(now - 60 * 1000).toISOString(),
        roomZone: 'study-desk',
      },
      {
        id: 'agent4',
        name: '卧室预览位',
        role: 'work',
        emoji: '',
        fallbackIcon: '\u{1F916}',
        theme: 'pixel-room-preview',
        status: 'sleeping',
        activityLabel: '卧室图标预览中',
        currentTask: '展示第 4 个图标',
        isDefault: false,
        canDispatchTo: [],
        lastSeenAt: new Date(now - 5 * 60 * 1000).toISOString(),
        roomZone: 'bed',
      },
    ],
    events: [
      {
        id: 'evt-1',
        agentId: 'agent1',
        type: 'task-start',
        text: '开始完善开发与生产隔离方案',
        at: updatedAt,
      },
      {
        id: 'evt-2',
        agentId: 'agent3',
        type: 'status-change',
        text: '切换到思考状态',
        at: updatedAt,
      },
      {
        id: 'evt-3',
        agentId: 'agent4',
        type: 'preview',
        text: '在卧室放置第 4 个图标预览',
        at: updatedAt,
      },
    ],
    gateway: {
      status: 'connected',
      connected: true,
      metaAvailable: true,
      metaErrors: [],
      metaMethodErrors: {
        status: null,
        health: null,
        systemPresence: null,
      },
      activeSessionCount: 3,
      totalSessionCount: 3,
      configuredChannelCount: 1,
      healthyChannelCount: 1,
      connectionCount: 2,
      heartbeatEvery: '30m',
      defaultAgentId: 'agent1',
      lastSuccessAt: updatedAt,
    },
  })
}
